name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use the Node.js version required by your project

      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: npm run build

      - name: Remove symlinks in build directory
        run: |
          find build -type l -delete

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1